name: Discussion Validation

on:
  discussion:
    types:
      - created

jobs:
  generate-and-validate-prompt:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate prompt.json and validate
        run: node generate-validate.js
        
      - name: List files in working directory
        run: ls -R

