name: Discussion on Comment

on:
  discussion:
    types:
      - created 
      
jobs:
  triage:
    if: >-
      github.event.discussion.category.name == 'General'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get discussion information
        id: discussion-info
        uses: Swapnil-Devops/rest-api-demo@main
        with:
          PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: verify Labels
        run: echo "${{ steps.discussion-info.outputs.disc_labels}}" 
