name: Generate and Validate Prompt

on:
  discussion:
    types:
      - created

jobs:
  generate-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install jsonschema

      - name: Generate and Validate Prompt JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_PAYLOAD_PATH: ${{ github.event_path }}
        run: node .github/scripts/generate-validate-prompt.js $EVENT_PAYLOAD_PATH
